#!/usr/bin/env bash
# loops!!!!
x=1
while [ $x -le 20 ]
do
	x=$((x+1))
	case $x in
		4)
			echo "bad luck from China" ;;
		9)
			echo "bad luck from Japan" ;;
		17)
			echo "bad luck from Italy" ;;
	esac
done
